# k8s-tripfinder/jenkins-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-manual
  claimRef:                 # pre-bind to the Jenkins PVC name/namespace
    namespace: jenkins
    name: jenkins
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-REPLACE_ME   # <- inject from SSM at bootstrap
    fsType: ext4
  nodeAffinity:             # must match the EBS volume's AZ
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi
  storageClassName: jenkins-manual
  volumeMode: Filesystem

