apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: jenkins
  labels: { app: ngrok }
spec:
  replicas: 1
  selector:
    matchLabels: { app: ngrok }
  template:
    metadata:
      labels: { app: ngrok }
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:3
        args:
          - http
          - --domain=$(NGROK_DOMAIN)
          - http://jenkins.jenkins.svc.cluster.local:8080
        env:
          - name: NGROK_AUTHTOKEN
            valueFrom:
              secretKeyRef: { name: ngrok-secret, key: NGROK_AUTHTOKEN }
          - name: NGROK_DOMAIN
            valueFrom:
              secretKeyRef: { name: ngrok-secret, key: NGROK_DOMAIN }
        ports:
          - name: api
            containerPort: 4040
        readinessProbe:
          httpGet: { path: /api/tunnels, port: 4040 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /api/tunnels, port: 4040 }
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests: { cpu: 10m, memory: 32Mi }
          limits:   { memory: 128Mi }

