jenkins:
  systemMessage: "Managed via Configuration-as-Code"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "https://rationally-above-sheep.ngrok-free.app/"  # trailing slash is fine
  jobDsl:
    scriptSecurity: false
  gitHubConfiguration:                     # modern GitHub endpoint config
    endpoints:
      - name: "github"
        apiUri: "https://api.github.com"
        manageHooks: false                 # set true only if you want Jenkins to auto-create webhooks
        credentialsId: "github-token"      # optional for API calls

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              id: "github-token"
              secret: "${GITHUB_TOKEN}"    # <-- map this env var via Helm to your jenkins-github secret (key: pat)
              description: "GitHub Personal Access Token"
          - usernamePassword:
              id: "ecr-creds"
              username: "AWS"
              password: "${ECR_PASSWORD}"  # <-- map this env var via Helm to jenkins-ecr secret (key: password)
              description: "ECR login token"

jobs:
  - script: |
      multibranchPipelineJob('tripfinder-backend') {
        displayName('tripfinder-backend')
        branchSources {
          branchSource {
            source {
              github {
                id('tripfinder-backend-src')
                repoOwner('pmcann')
                repository('tripfinder-backend')
                credentialsId('github-token')
                configuredByUrl(false)
                traits {
                  gitHubBranchDiscovery { strategyId(1) }        // branches
                  gitHubPullRequestDiscovery { strategyId(1) }    // PRs
                }
              }
            }
          }
        }
        factory { workflowBranchProjectFactory { scriptPath('Jenkinsfile') } }
        orphanedItemStrategy { discardOldItems { numToKeep(10) } }
        triggers { periodicFolderTrigger { interval('1d') } }     // daily scan as safety net
      }

      multibranchPipelineJob('tripfinder-frontend') {
        displayName('tripfinder-frontend')
        branchSources {
          branchSource {
            source {
              github {
                id('tripfinder-frontend-src')
                repoOwner('pmcann')
                repository('tripfinder-frontend')
                credentialsId('github-token')
                configuredByUrl(false)
                traits {
                  gitHubBranchDiscovery { strategyId(1) }
                  gitHubPullRequestDiscovery { strategyId(1) }
                }
              }
            }
          }
        }
        factory { workflowBranchProjectFactory { scriptPath('Jenkinsfile') } }
        orphanedItemStrategy { discardOldItems { numToKeep(10) } }
        triggers { periodicFolderTrigger { interval('1d') } }
      }

