controller:
  image:
    tag: lts-jdk17

  # Stop the sidecar from writing extra JCasC files
  sidecars:
    configAutoReload:
      enabled: false

  # Web service exposure
  serviceType: NodePort
  servicePort: 8080
  nodePort: 32010

  # Plugins (keep the full set here so there's a single source of truth)
  installPlugins:
    - configuration-as-code
    - kubernetes
    - workflow-aggregator
    - git
    - git-client
    - docker-workflow
    - pipeline-utility-steps
    - pipeline-stage-view
    - credentials
    - credentials-binding
    - plain-credentials
    - ssh-credentials
    - scm-api
    - script-security
    - structs
    - token-macro
    - jackson2-api
    - snakeyaml-api
    - kubernetes-credentials-provider
    - job-dsl
    - github
    - github-branch-source
    - ansicolor
    - timestamper
    - matrix-auth

  # NOTE: No JCasC here. JCasC is defined only in values-kubecloud.yaml (Option B).

# Durable storage (your preserved EBS via PVC)
persistence:
  enabled: true
  existingClaim: jenkins

# RBAC so kubernetes-credentials-provider can read Secrets
rbac:
  create: true
  readSecrets: true

serviceAccount:
  create: true
  name: jenkins

