controller:
  # Environment wiring (no JCasC files here)
  containerEnv:
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-admin-secret
          key: jenkins-admin-password
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-github
          key: pat
    - name: ECR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-ecr
          key: password
    - name: JENKINS_UC
      value: "https://updates.jenkins.io"
    - name: JENKINS_UC_DOWNLOAD
      value: "https://updates.jenkins.io/download"
    - name: JENKINS_INCREMENTALS_REPO_MIRROR
      value: "https://repo.jenkins-ci.org/incrementals"

  admin:
    existingSecret: jenkins-admin-secret
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  installPlugins:
    - configuration-as-code
    - job-dsl
    - workflow-aggregator
    - git
    - github
    - github-branch-source
    - branch-api
    - scm-api
    - kubernetes

  JCasC:
    enabled: true
    configScripts:
      casc: |-
        # PASTE THE ENTIRE CONTENTS OF jenkins-casc.yaml BELOW THIS LINE
        jenkins:
          systemMessage: "Managed via Configuration-as-Code"
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "${JENKINS_ADMIN_PASSWORD}"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

        unclassified:
          location:
            url: "https://rationally-above-sheep.ngrok-free.app/"
          gitHubConfiguration:
            endpoints:
              - name: "github"
                apiUri: "https://api.github.com"

        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "github-token"
                      username: "pmcann"
                      password: "${GITHUB_TOKEN}"
                      description: "Github login token"
                  - usernamePassword:
                      id: "ecr-creds"
                      username: "pmcann"
                      password: "${ECR_PASSWORD}"
                      description: "ECR login token"
    
persistence:
  enabled: true
  existingClaim: jenkins

