controller:
  containerEnv:
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-admin-secret
          key: jenkins-admin-password
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-github
          key: pat
    - name: ECR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-ecr
          key: password
  admin:
    existingSecret: jenkins-admin-secret
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  installPlugins:
    - kubernetes
    - configuration-as-code
    - workflow-aggregator
    - git
    - git-client
    - pipeline-utility-steps
    - pipeline-stage-view
    - credentials-binding
    - github
    - github-branch-source
    - ansicolor
    - timestamper
    - matrix-auth
    - kubernetes-credentials-provider
    - job-dsl                 # <-- REQUIRED for JCasC 'jobs:' block
  javaOpts: "-Djenkins.install.runSetupWizard=false"
  JCasC:
    configScripts:
      kubernetescloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                webSocket: true

