persistence:
  enabled: false

controller:
  ingress:
    enabled: true
    # modern style (optional but recommended)
    ingressClassName: traefik
    # If your chart version only supports annotations/hostName, keep your current block.
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - jenkins.your-domain.com

  # use 'containerEnv' if 'extraEnv' isn't recognized in your chart version
  containerEnv:
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-admin-secret
          key: password
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-github
          key: pat
    - name: ECR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-ecr
          key: password

  installPlugins:
    - configuration-as-code
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      casc: |
        jenkins:
          systemMessage: "⚙️ Managed via Configuration-as-Code"
        securityRealm:
          local:
            allowsSignup: false
            users:
              - id: "admin"
                password: "${JENKINS_ADMIN_PASSWORD}"
        authorizationStrategy:
          loggedInUsersCanDoAnything:
            allowAnonymousRead: false
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      id: "github-token"
                      secret: "${GITHUB_TOKEN}"
                      description: "GitHub Personal Access Token"
                  - usernamePassword:
                      id: "ecr-creds"
                      username: "AWS"
                      password: "${ECR_PASSWORD}"
                      description: "ECR login token"
        unclassified:
          location:
            url: "https://jenkins.your-domain.com"

