controller:
  containerEnv:
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-admin-secret
          key: jenkins-admin-password
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-github
          key: pat
    - name: ECR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-ecr
          key: password
  admin:
    existingSecret: jenkins-admin-secret
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  installPlugins:
    - kubernetes
    - configuration-as-code
    - workflow-aggregator        # Pipeline (all core pipeline bits)
    - git                        # Git client for jobs
    - git-client                 # Git plumbing
    - pipeline-utility-steps     # handy steps (readYaml, writeYaml, etc.)
    - pipeline-stage-view        # pretty pipeline UI
    - credentials-binding        # bind creds as env vars in pipelines
    - github                     # GitHub integration (webhooks, status)
    - github-branch-source       # multibranch / org jobs from GitHub
    - ansicolor                  # colorized console logs (nice to read)
    - timestamper                # enables options { timestamps() }
    - matrix-auth                # fine-grained RBAC if you want later
    - kubernetes-credentials-provider  # <-- exposes K8s Secrets as Jenkins credentials
  javaOpts: "-Djenkins.install.runSetupWizard=false"
  JCasC:
    configScripts:
      kubernetescloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                webSocket: true

