# Loki for small, ephemeral clusters — single-binary, NO PV, 7-day retention (best-effort)
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    retention_period: 168h   # 7 days (only as long as the pod lives)

singleBinary:
  replicas: 1
  # **No persistent volume** — keep data on container’s ephemeral storage
  persistence:
    enabled: false

# Ensure scalable topology is OFF
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

# Turn off caches used by scalable mode
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Keep these on (optional but handy)
gateway:
  enabled: true
lokiCanary:
  enabled: true

# Optional: expose Loki metrics to your Prom stack
serviceMonitor:
  enabled: true

