apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-manifests
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/pmcann/Linux-Scripts.git
    targetRevision: main
    path: k8s-monitoring
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
