apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tripfinder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pmcann/Linux-Scripts.git
    targetRevision: main
    path: k8s-tripfinder
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

