server:
  service:
    type: NodePort
    # Fixed NodePorts (must be in 30000–32767 and allowed in your SG)
    nodePortHttp: 32011
    nodePortHttps: 32444
    # Optional, but fine to keep explicit:
    servicePortHttp: 80
    servicePortHttps: 443

  # Disable ingress for now (no DNS). Flip to true later if you use Traefik/Ingress.
  ingress:
    enabled: false

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

