server:
  service:
    type: NodePort
    nodePortHttp: 32011     # pick any free port in 30000-32767
    nodePortHttps: 32444

  # Optional: if the chart exposes both http/https, default is fine.
  # servicePortHttp: 80
  # servicePortHttps: 443

# Disable ingress for now (no DNS). Re-enable later if you want.
server:
  ingress:
    enabled: false

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

