apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tripfinder-backend
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: tripfinder-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
