grafana:
  adminPassword: "prom-operator"
  defaultDashboardsEnabled: true
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 32001
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      isDefault: false
      jsonData:
        maxLines: 1000

prometheus:
  service:
    type: NodePort
    nodePort: 32002
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

